### ISSUE TITLE
Emojis in generated response getting replace with � replacement character

### ISSUE THREAD

**Issue by joncrangle** [nath1295/MLX-Textgen#5]
Thanks for you work on this project.

I've been trying to figure out why the `tokenizer.batch_decode` doesn't seem to be be decoding emojis properly for me. I'm using:

```yaml
- model_id_or_path: mlx-community/Meta-Llama-3.1-8B-Instruct-8bit
  tokenizer_id_or_path: null
  adapter_path: null
  quant: q8
  revision: null
  model_name: null
  model_config: null
  tokenizer_config: null
```

```
Prompt: show me some emojis for clothes
Response: 
Here are some emojis for clothes:

T-shirt: ������
Dress: ��
Pants: ��
Skirt: ��
Jacket: ��
Coat: ���
Hat: ���
Scarf: ���
Socks: ��
Shoes: ��
```

I tried debugging and logging some print statements with the raw bytes for generated text with emojis, but haven't been able to figure out why they are being replaced with replacement characters.

```
Token: [27623], Decoded:  �, Raw Bytes: b' \xef\xbf\xbd'
Generated Tokens: [[27623]]
Decoded Tokens: [' �']
Emoji detected in token stream.
Current Generated Text: [' �']
Token: [242], Decoded: �, Raw Bytes: b'\xef\xbf\xbd'
Generated Tokens: [[242]]
Decoded Tokens: ['�']
Emoji detected in token stream.
Current Generated Text: ['�']
```

Wondering if anyone has experienced the same issues?
